name: Pack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: mvn test -Dgroups=pipeline --batch-mode
      env:
        appSid: ${{secrets.appSidProd}}
        appKey: ${{secrets.appKeyProd}}
        apiBaseUrl: "https://api.aspose.cloud"
    - name: Pack
      run: |
        mvn package -DskipTests --batch-mode
        cp pom.xml aspose-email-cloud-0.0.1.pom
    - name: Zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./package.zip ./target/*.jar aspose-email-cloud-0.0.1.pom
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: package.zip
